blog/urls.py
from django.conf.urls import url
from .views import post_list, PostDetailView

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', post_list, name='list_post_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name="post_detail"),
]

cart/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_done

urlpatterns = [
    url(r'^$', cart_home, name='cart_home'),
    url(r'^update/$', cart_update, name='cart_update'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done, name='checkout_success'),

]

my_korea/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page
from cart.views import cart_detail_api_view
from django.views.generic import RedirectView
from e_marketing.views import MailchimpWebhookView


urlpatterns = [
    url(r'', include('products.urls', namespace='product')),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # редирект на кастомную url
    # url(r'^accounts/', RedirectView.as_view(url='/account')),
    # по дефолту в Джанге url идет /accounts/...
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^api/cart/', cart_detail_api_view, name='api-cart'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^webhook/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product

User = settings.AUTH_USER_MODEL


# class CartManager(models.Manager):
#     def new_or_get(self, request):
#         cart_id = request.session.get('cart_id', None)
#         qs = self.get_queryset().filter(id=cart_id)
#         if qs.count() == 1:
#             new_object = False
#             cart_object = qs.first()
#             if request.user.is_authenticated() and cart_object.user is None:
#                 cart_object.user = request.user
#                 cart_object.save()
#         else:
#             cart_object = Cart.objects.new(user=request.user)
#             new_object = True
#             request.session['cart_id'] = cart_object.id
#         return cart_object, new_object
#
#     def new(self, user=None):
#         user_object = None
#         if user is not None:
#             if user.is_authenticated():
#                 user_object = user
#         return self.model.objects.create(user=user_object)

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_object = False
            cart_object = qs.first()
            if request.user.is_authenticated() and cart_object.user is None:
                user_cart = self.model.objects.filter(user=request.user).first()
                if user_cart is not None:
                    cart_object.products.add(*user_cart.products.all())
                    cart_object.user = request.user
                    cart_object.save()
                    user_cart.delete()
                else:
                    cart_object.user = request.user
                    cart_object.save()
        else:
            cart_object = Cart.objects.new(user=request.user)
            new_object = True
            request.session['cart_id'] = cart_object.id
        return cart_object, new_object

    def new(self, user=None):
        user_object = None
        if user is not None:
            if user.is_authenticated():
                cart_object = self.model.objects.filter(user=user).first()
                if cart_object is not None:
                    return cart_object
                user_object = user
        return self.model.objects.create(user=user_object)


class Cart(models.Model):
    user     = models.ForeignKey(User, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    total    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated  = models.DateTimeField(auto_now=True)
    timestamp= models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'Корзины'

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        instance.total = total
        instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Cart
from orders.models import Order
from products.models import Product
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address


def cart_detail_api_view(request):
    cart_object, new_object = Cart.objects.new_or_get(request)
    products = [
        {
        'id': x.id,
        'url': x.get_absolute_url(),
        'name': x.title,
        'price': x.price
        } for x in cart_object.products.all()]

    cart_data = {'products': products, "total": cart_object.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_object, new_object = Cart.objects.new_or_get(request)

    return render(request, 'cart/home_cart.html', {"cart": cart_object})


def cart_update(request):
    product_id = request.POST.get('product')

    if product_id is not None:
        try:
            product_object = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print('Данный продукт отсутствует')
            return redirect('cart:cart_home')
        cart_object, new_object = Cart.objects.new_or_get(request)
        if product_object in cart_object.products.all():
            cart_object.products.remove(product_object)
            added = False
        else:
            cart_object.products.add(product_object)
            added = True
        request.session['cart_items'] = cart_object.products.count()
        if request.is_ajax():
            print('Ajax request')
            json_data = {
                "added": added,
                'removed': not added,
                'cartItemCount': cart_object.products.count()
            }
            return JsonResponse(json_data, status=200)
            #return JsonResponse({'message': 'Error 400'}, status_code=400)
    return redirect("cart:cart_home")


def checkout_home(request):
    cart_object, cart_created = Cart.objects.new_or_get(request)
    order_object = None
    if cart_created or cart_object.products.count() == 0:
        return redirect("cart:cart_home")

    login_form = LoginForm(request=request)
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_object, order_object_created = Order.objects.new_or_get(billing_profile, cart_object)
        if shipping_address_id:
            order_object.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_object.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_object.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_object.check_done()
        if is_done:
            order_object.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:checkout_success")

    context = {
        "order": order_object,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        'address_qs': address_qs
    }
    return render(request, "cart/checkout.html", context)


def checkout_done(request):
    return render(request, "cart/checkout_done.html", {})

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    {% if not billing_profile %}
        <div class="row text-center">
            <div class="col-12 col-md-6">
                <p class="lead">Войти</p>
                {% include 'accounts/snippets/form.html' with form=login_form  next_url=request.build_absolute_uri %}
            </div>
            <div class="col-12 col-md-6">
                <p class="lead">Продолжить гостем
                {% url 'guest_register' as guest_register_url %}
                {% include 'accounts/snippets/form.html' with form=guest_form  next_url=request.build_absolute_uri action_url=guest_register_url %}
            </div>
        </div>
    {% else %}
        {% if not order.shipping_address %}

         <div class='row'>
            <<div class='col-md-6 mx-auto col-10'>
                <p>Номер вашего заказа: {{ order.order_id }}</p>
                <p class='lead'>Адрес доставки</p>
                <hr/>
            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
             {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
         </div>

         </div>


        {% elif not order.billing_address %}
        <div class='row'>
            <div class='col-md-6 mx-auto col-10'>
                <p class='lead'>Billing Address</p>
                <hr/>
            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
                {% url 'checkout_address_reuse' as checkout_address_reuse %}
                {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
            </div>
        </div>
        {% else %}
            <div class='row'>
                <div class='col-md-6 mx-auto col-10 '>
                <h1 class="text-center">Оформление заказа</h1>
                <hr>
                <p>Продукты: {% for product in order.cart.products.all %}{{ product }}
                    {% if not forloop.last %},
                    {% endif %}
                {% endfor %}
                </p>
                <p>Адрес доставки: {{ order.shipping_address.get_address }}</p>
                <p>Стоимость товаров: {{ order.cart.total }}</p>
                <p>Стоимость доставки: {{ order.shipping_total }}</p>
                <p>К оплате: {{ order.total }}</p>
                <form class='form text-center' method='POST' action="">{% csrf_token %}
                    <button type='submit' class="btn btn-success ">Подтвердить</button>
                </form>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

cart/templates/cart/checkout_done.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

        <div class="d-flex justify-content-center">
            <div class="p-2">
            <h1 class="display-3 text-center">Спасибо за ваш заказ!</h1>
            </div>
        </div>
                <div class="d-flex justify-content-center">

                        <div class="p-2">
                            <p class="text-center">В ближайщее время с вами свяжется наш менеджер для уточнения деталей.</p>
                            <h1 class="text-center"><i class="far fa-thumbs-up"></i></h1>
                        </div>
                </div>




{% endblock %}

cart/templates/cart/home_cart.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="container">

            <h1>Корзина</h1>
            {% if cart.products.exists %}
                <div class="card">
                    <div class="table-responsive">

                        <table class="table table-bordered table-light" id="cart-table" style="background-color: ghostwhite;">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Название</th>
                          <th scope="col">Цена</th>
                        </tr>
                      </thead>
                      <tbody class="cart-body">
                      {% for product in cart.products.all %}
                        <tr class="cart-product">
                          <th scope="row">{{ forloop.counter }}</th>
                          <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                              {% include 'cart/snippets/remove-product.html' with product_id=product.id %}
                          </td>

                          <td>{{ product.price }}</td>
                        </tr>
                      {% endfor %}
                        <tr>
                          <td colspan="2"></td>
                          <td><b>Сумма</b> <span class="cart-total">{{ cart.total }}</span></td>
                        </tr>
                        <tr>
                          <td colspan="2"></td>
                          <td><a class="btn btn-block btn-success" href="{% url 'cart:checkout' %}">Оформить заказ</a></td>
                        </tr>
                      </tbody>
                    </table>
                        <div class="cart-item-remove-form" style="display: none">
                            {% include 'cart/snippets/remove-product.html' %}
                        </div>
                    {% else %}
                        <p class="lead">Cart is empty</p>
                    {% endif %}
        </div>

{% endblock %}