blog/urls.py
from django.conf.urls import url
from .views import post_list, PostDetailView

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', post_list, name='list_post_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name="post_detail"),
]

my_korea/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page
from cart.views import cart_detail_api_view
from django.views.generic import RedirectView
from e_marketing.views import MailchimpWebhookView


urlpatterns = [
    url(r'', include('products.urls', namespace='product')),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # редирект на кастомную url
    # url(r'^accounts/', RedirectView.as_view(url='/account')),
    # по дефолту в Джанге url идет /accounts/...
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^api/cart/', cart_detail_api_view, name='api-cart'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^webhook/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import random
import os
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from my_korea.utils import unique_slug_generator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    # print(instance)
    # print(filename)
    new_filename = random.randint(1, 55555555555555)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return "posts/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(blank=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:list_post_by_category', args=[self.slug])




class Post(models.Model):
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, blank=True, null=True)
    title       = models.CharField(max_length=120)
    picture     = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    information = models.TextField(blank=True, null=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    slug        = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)
        verbose_name = 'пост'
        verbose_name_plural = 'Посты'

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id, self.slug])


def post_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(post_pre_save_receiver, sender=Post)


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(category_pre_save_receiver, sender=Category)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import ListView, DetailView
from .models import Post, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    posts = Post.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        posts = Post.objects.filter(category=category)

    # pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 3)

    try:
        pag_post = paginator.page(page)
    except PageNotAnInteger:
        pag_post = paginator.page(1)
    except EmptyPage:
        pag_post = paginator.page(paginator.num_pages)
    # конец pagination

    context = {
        'category': category,
        'categories': categories,
        'posts': pag_post,
    }
    return render(request, 'post/post_list.html', context)


class PostListView(ListView):
    template_name = 'post/post_list.html'
    paginate_by = 3

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Post.objects.all()


class PostDetailView(DetailView):
    template_name = 'post/post_detail.html'
    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Post.objects.get(slug=slug)
        except Post.DoesNotExist:
            raise Http404("Ничего не найдено")
        except Post.MultipleObjectsReturned:
            qs = Post.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404('Произошла ошибка')
        return instance

blog/templates/post/post_detail.html
{% extends "base.html" %}

{% block content %}

  <article>

    <div class="container">

        <div class="row">

            <div class="col-lg-8 col-md-10 mx-auto">
                {% if post.picture %}
                        <img class="img-fluid" src="{{ post.picture.url}}">
                    {% endif %}
                <h1 class="display-5 text-center">{{ post.title }}</h1><br>

                <p class="lead">{{ post.information }}</p>
                <hr>
                Добавлено: {{ post.timestamp|date:"SHORT_DATE_FORMAT" }}
            </div>


        </div>
    </div>
  </article>

{% endblock %}

blog/templates/post/post_list.html
{% extends "base.html" %}
{% block title %}Blog{% endblock %}


{% block content %}

   <div class="container pt-5">

        <!--Grid row-->
            <div class="row">


                <div class="col-12 col-md-4 сol-lg-4">
                    <div class="card my-4">
                        <h5 class="card-header">Категории</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="navbar-nav mr-auto">
                                    <li class="nav-item {% if not category %}active{% endif %}" >
                                      <a class="nav-link" href="{% url 'blog:post_list' %}">Все</a>
                                    </li>
                                  {% for c in categories %}
                                    <li class="nav-item {% if category.slug == c.slug %}active{% endif %}">
                                      <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.title }}</a>
                                    </li>
                                  {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>

                    </div>
                </div>
                <div class="col-md-8 ">

                      <!--Grid column-->
                        {% for post in posts %}
                                {% include 'snippets/card_for_post.html' with instance=post %}
                        {% endfor %}
                </div>
            </div>
   </div>


        <!-- От сюда идет pagination -->
    {%  if posts.has_other_pages  %}
        <hr>
        <nav class="d-flex justify-content-center wow fadeIn" aria-label="Page navigation">
            <ul class="pagination pg-blue">
                {% if posts.has_previous %}
                   <li class="page-item">
                        <a class="page-link" href="?page={{ posts.previous_page_number }}">Предыдущая</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Предыдущая</a>
                    </li>
                    {% endif %}
                    {% for i in posts.paginator.page_range %}
                        {% if posts.number == i %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    {% if posts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.next_page_number }}">Следующая</a>
                        </li>
                    {% else %}
                         <li class="page-item disabled">
                             <a class="page-link" href="#">Следующая</a>
                         </li>
                    {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}