blog/urls.py
from django.conf.urls import url
from .views import post_list, PostDetailView

urlpatterns = [
    url(r'^$', post_list, name='post_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', post_list, name='list_post_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name="post_detail"),
]

my_korea/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView, RegisterView, GuestRegisterView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page
from cart.views import cart_detail_api_view
from django.views.generic import RedirectView
from e_marketing.views import MailchimpWebhookView


urlpatterns = [
    url(r'', include('products.urls', namespace='product')),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # редирект на кастомную url
    # url(r'^accounts/', RedirectView.as_view(url='/account')),
    # по дефолту в Джанге url идет /accounts/...
    url(r'^accounts/', include('accounts.urls', namespace='account')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^api/cart/', cart_detail_api_view, name='api-cart'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^webhook/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import product_list, ProductDetailView


urlpatterns = [
    url(r'^$', product_list, name='list'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', product_list, name='list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', ProductDetailView.as_view(), name="detail"),
]

products/models.py
import random
import os
from django.db.models import Q
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.urls import reverse
from my_korea.utils import unique_slug_generator


def get_filename_ext(filepath):
        base_name = os.path.basename(filepath)
        name, ext = os.path.splitext(base_name)
        return name, ext


def upload_image_path(instance, filename):
    #print(instance)
    #print(filename)
    new_filename = random.randint(1, 55555555555555)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return "products/{new_filename}/{final_filename}".format(
        new_filename=new_filename,
        final_filename=final_filename
    )


class Category(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(blank=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:list_by_category', args=[self.slug])


class ProductQuerySet(models.query.QuerySet):

    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
            lookups = (Q(title__icontains=query) |
                       Q(description__icontains=query) |
                       Q(tag__title__icontains=query))
            return self.filter(lookups).distinct()


class ProductManager(models.Manager):

    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):  # Product.objects.featured()
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, blank=True, null=True)
    title       = models.CharField(max_length=120)
    slug        = models.SlugField(blank=True, unique=True)
    description = models.TextField(null=True)
    price       = models.DecimalField(max_digits=20, decimal_places=2, default=49.99)
    sale_price  = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    image       = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    active      = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    status      = models.CharField(max_length=120, blank=True, null=True)

    objects = ProductManager()

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse('product:detail', args=[self.id, self.slug])

    def __str__(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)


def category_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(category_pre_save_receiver, sender=Category)

products/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from cart.models import Cart
from analytics.mixins import ObjectViewedMixin
from .models import Product, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    # pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)

    try:
        pag_prod = paginator.page(page)
    except PageNotAnInteger:
        pag_prod = paginator.page(1)
    except EmptyPage:
        pag_prod = paginator.page(paginator.num_pages)
    # конец pagination

    # корзина
    cart_object, new_object = Cart.objects.new_or_get(request)

    context = {
        'category': category,
        'categories': categories,
        'products': pag_prod,
        'cart': cart_object
    }
    return render(request, 'products/list.html', context)

# не знаю как заставить сортировать по категориям используя классы
class ProductListView(ListView):
    template_name = 'products/list.html'
    paginate_by = 6

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_object, new_object = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_object
        #тестовая часть для добавления категорий
        # category = None
        # categories = Category.objects.all()
        # products = self.get_queryset()
        # if category_slug:
        #     category = get_object_or_404(Category, slug=category_slug)
        #     products = Product.objects.filter(category=category)
        # context['category'] = category
        # context['categories'] = categories
        # context['products'] = products
        return context

    #Вызывать эту функцию нужно только когда хочешь добавить новую инфу в модель
    # def get_context_data(self, *args, **kwargs):
    #     context = super(ProductListView, self).get_context_data(*args, **kwargs)
    #     return context


class ProductDetailView(ObjectViewedMixin, DetailView):
    queryset = Product.objects.all()
    template_name = 'products/details.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        cart_object, new_object = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_object
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Ничего не найдено")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404('Произошла ошибка')
        return instance


class UserHistoryProductView(LoginRequiredMixin, ListView):
    template_name = 'products/user_history.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        views = request.user.objectview_set.by_model(Product)
        #viewed_ids = [x.object_id for x in views]
        return views

    def get_context_data(self, *args, **kwargs):
        context = super(UserHistoryProductView, self).get_context_data(*args, **kwargs)
        cart_object, new_object = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_object
        return context

products/templates/products/details.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

     <main class="mt-5 pt-2">

        <div class="container dark-grey-text mt-1">

              <!--Grid row-->
              <div class="row wow fadeIn">

                <!--Grid column и картинка-->
                <div class="col-lg-6 col-md-6 mb-4">
                    {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.title }}" class="img-fluid">
                    {% endif %}
                </div>

                  <!--Grid column-->
                <div class="col-lg-6 col-md-6 mb-4">

                  <!--Content-->
                  <div class="p-4">

                        <div class="text-center mb-3">
                            <a href="">
                                <span class="badge purple mr-1">{{ product.category }}</span>
                            </a>
                            {% if product.status != None %}
                            <a href="">
                                <span class="badge purple mr-1">{{ product.status }}</span>
                            </a>
                            {% endif %}
                        </div>
                  <div class="text-center">
                      <p class="lead">
                          {% if product.sale_price > 0 %}
                          <span class="mr-1">
                            <del>{{ product.price }}</del>
                          </span>
                          <span>{{ product.sale_price }}</span>
                          {% else %}
                          <span>{{ product.price }}</span>
                          {% endif %}
                      </p>

                      {% include 'snippets/cart_update.html' with product=object cart=cart %}
                  </div>


                      <p class="lead font-weight-bold">Описание</p>

                      <p class="lead">{{ product.description }}</p>



                  </div>
                </div>
              </div>
        </div>
     </main>



{#<h1>{{ product.title }}</h1><br>#}
                      {#Добавлено: {{ product.timestamp|date:"SHORT_DATE_FORMAT" }} <br>#}
                      {#               {{ product.price }}<br> #}




            {# <p>{{ product.description|linebreaks }}</p> #}


{% endblock %}

products/templates/products/featured_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {{ product.title }}<br>
    {{ product.price }}<br>
    {% if product.image %}
        <img src="{{ product.image.url}}">
    {% endif %}
</body>
</html>

products/templates/products/list.html
{% extends "base.html" %}

{% block content %}

    <div class="container">

    <!-- Тестовый html -->

          <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Категории:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if not category %}active{% endif %}" >
              <a class="nav-link" href="{% url 'product:list' %}">Все</a>
            </li>
          {% for c in categories %}
            <li class="nav-item {% if category.slug == c.slug %}active{% endif %}">
              <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.title }}</a>
            </li>
          {% endfor %}
          </ul>
        <!-- Collapsible content -->
        </div>
      </nav>
      <!--/.Navbar-->

      <!-- Тут идет список товаров -->

        <section class="text-center mb-4">

        <!--Grid row-->
            <div class="row wow fadeIn">
          <!--Grid column-->
                    {% for prod in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            {% include 'snippets/card.html' with instance=prod %}
                        </div>
                    {% endfor %}
            </div>
        </section>

    </div>

    <!-- От сюда идет pagination -->
    {%  if products.has_other_pages  %}
        <hr>
        <nav class="d-flex justify-content-center wow fadeIn" aria-label="Page navigation">
            <ul class="pagination pg-blue">
                {% if products.has_previous %}
                   <li class="page-item">
                        <a class="page-link" href="?page={{ products.previous_page_number }}">Предыдущая</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Предыдущая</a>
                    </li>
                    {% endif %}
                    {% for i in products.paginator.page_range %}
                        {% if products.number == i %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    {% if products.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ products.next_page_number }}">Следующая</a>
                        </li>
                    {% else %}
                         <li class="page-item disabled">
                             <a class="page-link" href="#">Следующая</a>
                         </li>
                    {% endif %}
            </ul>
        </nav>
    {% endif %}


{% endblock %}

products/templates/products/user_history.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    <div class="container">
        <div class="row">
        <div class="col-12 my-2">
            <h1>Просмотренные продукты</h1>
            <hr>
        </div>

            {% for prod in object_list %}
                <div class="col my-2">
                    {% include 'snippets/card.html' with instance=prod.content_object %}
                </div>
            {% endfor %}
        </div>
</div>
{% endblock %}